### PR TITLE
add Messaging Estimated Wait Time

### PR DESCRIPTION
**Pull request by WildYorkies**
Was a little tricky because it has a different service name and base uri structure from the other API methods.

Tested and is working now, though.

### CODE REVIEW

**Comment by WildYorkies** [comment]
@danielkerwin Did you get a chance to look at this? I haven't had luck getting access to the original repo yet.

**Comment by danielkerwin** [comment]
Crazy busy - but reviewing

**Comment by charleigh8** [comment]
Looks good btw. Thanks for adding this Cale. @danielkerwin let me know you've updated to pypi?

**Comment by danielkerwin** [comment]
@charleigh8 pushed to pypi

**Pull request merged**
